language: python
python:
  - "3.6"

cache: pip

services:
  - docker

env:
  - CONF=sync
  - CONF=async

before_install:
  - make images
  - docker-compose -f .travis/docker-compose.yaml up -d

install:
  - pip install -e .[confluent-kafka]
  - pip install kafka

script:
  - cd tests; python -m unittest; cd -
  - make tests

