consumer:
  class: tdm_ingestion.consumers.confluent_kafka_consumer.KafkaConsumer
  args:
    bootstrap_servers:
      - kafka:29092
    topics:
      - test
storage:
  class: tdm_ingestion.storage.base.CachedStorage
  args:
    client:
      class: tdm_ingestion.storage.remote_client.Client
      args:
        url: http://web:8000

ingester:
  process:
    timeout_s: 20
    max_records: 10
